### ISSUE TITLE
No object detect

### ISSUE THREAD

**Issue by tommywu052** [cookieofcode/LabAssistVision#12]
## No object detect when I launch the app on HL2
1. Is the default behavior using Custom vision cloud service ? If that, in addition to update endpoint and key , should I download the offline onnx model to asset package ?
2. How to use the local onnx model instead of cloud service ? choose "Use Local Model" in MR toolkit extension ?

**Comment by cookieofcode** [comment]
Hi @tommywu052,

The default behavior is the [CustomVisionObjectDetectionService](https://github.com/cookieofcode/LabAssistVision/blob/main/Assets/MixedRealityToolkit.Generated/Extensions/Detection/CustomVisionObjectDetectionService.cs). Running a local ONNX model was still very experimental, and still needs proper implementation. I added [CustomVisionLocal](https://github.com/cookieofcode/LabAssistVision/blob/main/Assets/LabAssistVision/Experimental/CustomVisionLocal.cs) as a work in progress for a colleague.

1. Please use the [CustomVision](https://www.customvision.ai/) cloud service. You'll need to train one by yourself and generate and configure the endpoint and key.
2. As mentioned, the local model is experimental and may not work out of the box. If you want to work on that, configure the [CustomVisionLocal](https://github.com/cookieofcode/LabAssistVision/blob/main/Assets/LabAssistVision/Experimental/CustomVisionLocal.cs) as object detector in the custom vision object detection service. Export the model on CustomVision as ONNX in the compact domain.

I'll archive this project as it is no longer in development and I do not have access to a HoloLens anymore.
