### ISSUE TITLE
hello，Can I use my own server for this project?

### ISSUE THREAD

**Issue by pkuma** [cookieofcode/LabAssistVision#9]
For example, using yolov3 instead of custom vision on my own server

I'm a novice and don't know much about hololens2. Is my idea feasible?

Thank you very much for your reply

**Comment by cookieofcode** [comment]
Hi @pkuma 

Sorry for the late response. Sure this should be feasible, but this will need some adjustments to the project. You may want to take a look at [https://github.com/doughtmw/YoloDetectionHoloLens-Unity](https://github.com/doughtmw/YoloDetectionHoloLens-Unity).
